services:
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - web
    ports:
      - 80:80

  web:
    build: ./web
    container_name: web
    ports:
      - 2222:2222
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   environment:
  #     MONGO_INITDB_DATABASE: admin
  #   volumes:
  #     - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
  #     - ./mongo/mongo-data:/data/db
  #   # Start mongo with authentication enabled
  #   command: [mongod, --auth]